### ISSUE TITLE
Internal error in ShaderStages

### ISSUE THREAD

**Issue by alexandrasp** [rewin123/space_editor#120]
I cloned the code from the main branch and using the main described below run _cargo run_ aiming to build the project locally and got the error described in the log:

```
2023-12-16T02:32:08.570721Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-12-16T02:32:09.399009Z  INFO bevy_xpbd_plugin: Add bevy_xpbd_3d plugin to editor
BevyXpbdPlugin::build
2023-12-16T02:32:09.685914Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-12-16T02:32:09.944747Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 12.7.1 ", kernel: "21.6.0", cpu: "Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz", core_count: "4", memory: "16.0 GiB" }
2023-12-16T02:32:10.027637Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
2023-12-16T02:32:10.110476Z  WARN persistence: Persistence file not found at path editor.ron
2023-12-16T02:32:11.455278Z ERROR log: Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): new_render_pipeline_state: "Compiler encountered an internal error"
2023-12-16T02:32:11.455599Z ERROR log: Please report it to https://github.com/gfx-rs/naga
2023-12-16T02:32:11.455713Z ERROR log: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (1)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `alpha_blend_mesh_pipeline`
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"

', /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:3056:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45
```

**src/main.rs:**
```
use bevy::prelude::*;
use editor::simple_editor_setup;
use space_editor::SpaceEditorPlugin;

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins)
        .add_plugins(SpaceEditorPlugin)
        .add_systems(Startup, simple_editor_setup);
    app.run();
}
```

**Comment by naomijub** [comment]
@alexandrasp I think it might be happening because you dont have GPU, we can try to fix that

**Comment by naomijub** [comment]
@alexandrasp can you execute the program in nightly? I think this might have been addressed in a newer version.

Cargo +nightly run

**Comment by alexandrasp** [comment]
> @alexandrasp can you execute the program in nightly? I think this might have been addressed in a newer version.
> 
> Cargo +nightly run

Ok, done, but the error persists. 
[log.txt](https://github.com/rewin123/space_editor/files/13699456/log.txt)

**Comment by naomijub** [comment]
Can you try what @rewin123 suggested and execute a simple 3d example from bevy repo?

**Comment by alexandrasp** [comment]
@rewin123 @naomijub it works :)
<img width="1273" alt="Screen Shot 2023-12-18 at 11 50 10 PM" src="https://github.com/rewin123/space_editor/assets/6344218/e4ba4af7-79ee-417d-a4e3-736a98b8cb94">

```
Running `target/debug/space_editor`
2023-12-19T04:46:01.670049Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-12-19T04:46:02.400632Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-12-19T04:46:02.499160Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 12.7.1 ", kernel: "21.6.0", cpu: "Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz", core_count: "4", memory: "16.0 GiB" }
2023-12-19T04:50:17.939854Z  INFO bevy_window::system: No windows are open, exiting
2023-12-19T04:50:17.941151Z  INFO bevy_winit::system: Closing window 0v0
```

**Comment by rewin123** [comment]
Just in case:) 

I will create a separate branch, where I will disable things that theoretically can lead to problems and ask you to start this branch. So, we'll find the problem by the exception method then.

**Comment by rewin123** [comment]
@alexandrasp can you try to compile fix-internal-shader branch? 

In 4 tries, it will be possible to find the source of the bug (most likely)

**Comment by alexandrasp** [comment]
hey @rewin123  and @naomijub, I am back. 

I took the main branch and tried locally on the same Mac. First:

```
➜  space_editor git:(main) cargo run
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /Users/apereira/dev/space_editor/crates/editor_ui/Cargo.toml
workspace: /Users/apereira/dev/space_editor/Cargo.toml
warning: /Users/apereira/dev/space_editor/Cargo.toml: unused manifest key: workspace.dependencies.image.feature
   Compiling space_editor_ui v0.4.0 (/Users/apereira/dev/space_editor/crates/editor_ui)
error[E0308]: mismatched types
   --> crates/editor_ui/src/camera_view.rs:317:25
    |
317 |         scale_factor *= ratio;
    |                         ^^^^^ expected `f32`, found `f64`

error[E0277]: cannot multiply-assign `f32` by `f64`
   --> crates/editor_ui/src/camera_view.rs:317:22
    |
317 |         scale_factor *= ratio;
    |                      ^^ no implementation for `f32 *= f64`
    |
    = help: the trait `MulAssign<f64>` is not implemented for `f32`
    = help: the following other types implement trait `MulAssign<Rhs>`:
              <f32 as MulAssign>
              <f32 as MulAssign<&f32>>

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `space_editor_ui` (lib) due to 2 previous errors
```

If I change the code to `f64`, I take: 

```
2024-03-09T06:33:30.063761Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-03-09T06:33:31.583647Z  INFO space_bevy_xpbd_plugin: Add bevy_xpbd_3d plugin to editor
BevyXpbdPlugin::build
2024-03-09T06:33:32.053658Z  INFO bevy_winit::system: Creating new window "Space Editor" (0v1)
2024-03-09T06:33:32.148861Z  INFO space_editor_ui: Set start state
2024-03-09T06:33:32.149003Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 12.7.1 ", kernel: "21.6.0", cpu: "Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz", core_count: "4", memory: "16.0 GiB" }
2024-03-09T06:33:32.409675Z  WARN space_persistence: Persistence file not found at path editor.ron
2024-03-09T06:33:36.441172Z ERROR log: Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"
2024-03-09T06:33:36.441255Z ERROR log: Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): new_render_pipeline_state: "Compiler encountered an internal error"
2024-03-09T06:33:36.441307Z ERROR log: Please report it to https://github.com/gfx-rs/wgpu
2024-03-09T06:33:36.441415Z ERROR log: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (0)' panicked at /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = alpha_blend_mesh_pipeline
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"


note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Encountered a panic in system bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines!
thread 'Compute Task Pool (0)' panicked at /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/pipelined_rendering.rs:49:67:
called Result::unwrap() on an Err value: RecvError
thread 'main' panicked at /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.13/src/platform_impl/macos/app_state.rs:387:33:
called Result::unwrap() on an Err value: PoisonError { .. }
```

Do you have any ideas to fix it?

**Comment by naomijub** [comment]
The compilation error I have fixed already in main. The remaining issue I will try to investigate this week

**Comment by rewin123** [comment]
I found that we can request github CI to run on mac system. Will add this during #270

**Comment by alexandrasp** [comment]
@rewin123 @naomijub  https://github.com/gfx-rs/wgpu/issues/4817

**Comment by naomijub** [comment]
Mac CI even prints screenshots correctly, so I guess the issue points to the correct observation

**Comment by naomijub** [comment]
It seems that this issue is an Apple problem, as they restrict os/xcode updates on the machines that are older than X years. 

It seems there is nothing we can do but recommend Linux 😂
